---
name: "Testing Github Actions Workflow"

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: "Execute Date command"
        run: date
        shell: bash

      - name: "Display OS Details"
        run: cat /etc/os-release
        shell: bash

      - name: "Current user"
        run: whoami
        shell: bash

      - name: "Current working directory before checkout"
        run: |
          pwd
          ls -la

      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Current working directory after checkout"
        run: |
          pwd
          ls -la

      - name: "Installing Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: "Terraform version"
        run: terraform version

      - name: "Running script"
        run: |
          chmod +x script.sh
          ./script.sh
